package com.utils

object StringConstantsUtil {

  val WORKFLOW = "workflow"

  val CUSTOMER_RISK_RATINGS_WF ="CustomerRiskRatingsWF"

  val GLOBAL = "global"
  val MASTER = "master"
  val LOCAL = "local"
  val RUNMODE = "runMode"


  val INPUT_FILE_PATH = "input_feed"

  val CUSTOMER_OVERDRAFTS_CREDITLIMITS = ""
  val CUSTOMER_ACCOUNT_BALANCES=""
  val CUSTOMER_DEPOSITS_LOANS =""
  val CUSTOMER_DETAILS= "src/main/resources/input/application_record.csv"
  val CUSTOMER_KYC_RATINGS=""
  val CUSTOMER_LOAN_REPAYMENTS=""
  val CUSTOMER_INDUSTRY_OF_BUSINESS=""


  // OutDF one stage to another stage

  val CUSTOMER_OVERDRAFTS_CREDITLIMITS_DF = ""
  val CUSTOMER_ACCOUNT_BALANCES_DF = ""
  val CUSTOMER_DEPOSITS_LOANS_DF = ""
  val CUSTOMER_DETAILS_DF = ""
  val CUSTOMER_KYC_RATINGS_DF = ""
  val CUSTOMER_LOAN_REPAYMENTS_DF = ""
  val CUSTOMER_INDUSTRY_OF_BUSINESS_DF = ""

  val CUSTOMER_RATING_TRANSFORMER_DF = "customerRatingDF"



  val CUST_ID = "ID"
  val CODE_GENDER = "CODE_GENDER"
  val FLAG_OWN_CAR ="FLAG_OWN_CAR"
  val FLAG_OWN_REALTY = "FLAG_OWN_REALTY"
  val CNT_CHILDREN = "CNT_CHILDREN"
  val AMT_INCOME_TOTAL ="AMT_INCOME_TOTAL"
  val NAME_INCOME_TYPE ="NAME_INCOME_TYPE"
  val NAME_EDUCATION_TYPE ="NAME_EDUCATION_TYPE"
  val NAME_FAMILY_STATUS ="NAME_FAMILY_STATUS"
  val NAME_HOUSING_TYPE = "NAME_HOUSING_TYPE"
  val AGE_IN_DAYS = "AGE_IN_DAYS"
  val AGE_IN_YEARS ="AGE_IN_YEARS"
  val DAYS_EMPLOYED = "DAYS_EMPLOYED"
  val FLAG_MOBIL = "FLAG_MOBIL"
  val FLAG_WORK_PHONE = "FLAG_WORK_PHONE"
  val FLAG_PHONE  = "FLAG_PHONE"
  val FLAG_EMAIL = "FLAG_EMAIL"
  val OCCUPATION_TYPE = "OCCUPATION_TYPE"
  val CNT_FAM_MEMBERS = "CNT_FAM_MEMBERS"



}
