package com.utils

import java.text.SimpleDateFormat
import java.util.Calendar

object StringConstantsUtil {

  val dateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")

  val WORKFLOW = "workflow"

  val CUSTOMER_RISK_RATINGS_WF ="CustomerRiskRatingsWF"

  val GLOBAL = "global"
  val MASTER = "master"
  val LOCAL = "local"
  val RUNMODE = "runMode"

  val OUTPUT_PATH = "result_folder"

  val CUSTOMERDETAILS_FEED = "input_feed_customer"
  val INPUT_LOAN_DETAILS = "loan_details"
  val CUST_ACCOUNT_BALANCES_LOD_FEED = "loan_lod_feed"
  val CUST_LOB ="customer_lob"


  val CUSTOMER_DETAILS= "src/main/resources/input/customer_details.csv"



  // OutDF one stage to another stage


  val CUSTOMER_ACCOUNT_BALANCES_DF = "custRunningAccountStatusDf"
  val CUSTACCOUNTLOANDETAILS = "CUSTACCOUNTLOANDETAILS"
  val CUSTOMER_DETAILS_DF = "customerRefinedDf"


  val CUSTOMER_INDUSTRY_OF_BUSINESS_DF = "customerIndustryDetails"

  val CUSTOMER_RATING_TRANSFORMER_DF = "customerRiskRatingsrptDf"



  val CUST_ID = "ID"
  val CODE_GENDER = "CODE_GENDER"
  val FLAG_OWN_CAR ="FLAG_OWN_CAR"
  val FLAG_OWN_REALTY = "FLAG_OWN_REALTY"
  val CNT_CHILDREN = "CNT_CHILDREN"
  val AMT_INCOME_TOTAL ="AMT_INCOME_TOTAL"
  val NAME_INCOME_TYPE ="NAME_INCOME_TYPE"
  val NAME_EDUCATION_TYPE ="NAME_EDUCATION_TYPE"
  val NAME_FAMILY_STATUS ="NAME_FAMILY_STATUS"
  val NAME_HOUSING_TYPE = "NAME_HOUSING_TYPE"
  val AGE_IN_DAYS = "AGE_IN_DAYS"
  val AGE_IN_YEARS ="AGE_IN_YEARS"
  val DAYS_EMPLOYED = "DAYS_EMPLOYED"
  val FLAG_MOBIL = "FLAG_MOBIL"
  val FLAG_WORK_PHONE = "FLAG_WORK_PHONE"
  val FLAG_PHONE  = "FLAG_PHONE"
  val FLAG_EMAIL = "FLAG_EMAIL"
  val OCCUPATION_TYPE = "OCCUPATION_TYPE"
  val CNT_FAM_MEMBERS = "CNT_FAM_MEMBERS"
  val COUNTRY_CODE = "COUNTRY_CODE"

  val upd_ts = dateformat.format(Calendar.getInstance().getTime())

  val riskCountry = List("LIBYA","HAITI","CHAD")
  val moreAge = 60

  //ID,IS_SB_ACCOUNT,IS_OD_ACCOUNT,IS_RD_ACCOUNT,FLAG_NEGATIVE_BALANCE,FLAG_PERSONAL_LOAN,FLAG_LOAN_DEFAULT
  val IS_SB_ACCOUNT = "IS_SB_ACCOUNT"
  val IS_OD_ACCOUNT = "IS_OD_ACCOUNT"
  val IS_RD_ACCOUNT = "IS_RD_ACCOUNT"
  val FLAG_NEGATIVE_BALANCE = "FLAG_NEGATIVE_BALANCE"
  val FLAG_PERSONAL_LOAN = "FLAG_PERSONAL_LOAN"
  val FLAG_LOAN_DEFAULT = "FLAG_LOAN_DEFAULT"

  //ID,FD_AMT,RD_BALANCE,SB_CURRENT_BALANCE,SB_QUARTELY_BALANCE,OD_CURRENT_OUTSTANDING,OD_LIMIT,PERSONAL_LOAN_BALANCE
  val FD_AMT = "FD_AMT"
  val RD_BALANCE = "RD_BALANCE"
  val SB_CURRENT_BALANCE = "SB_CURRENT_BALANCE"
  val SB_QUARTELY_BALANCE = "SB_QUARTELY_BALANCE"
  val OD_CURRENT_OUTSTANDING = "OD_CURRENT_OUTSTANDING"
  val OD_LIMIT = "OD_LIMIT"
  val PERSONAL_LOAN_BALANCE = "PERSONAL_LOAN_BALANCE"

  //COUNTRY_CODE,CUSTOMER_COUNTRY_OF_BUSINESS,CUSTOMER_LOB,CUSTOMER_BUSINESS_ADDRESS,BUSINESS_TYPE
  val CUSTOMER_COUNTRY_OF_BUSINESS = "CUSTOMER_COUNTRY_OF_BUSINESS"
  val CUSTOMER_LOB = "CUSTOMER_LOB"
  val CUSTOMER_BUSINESS_ADDRESS = "CUSTOMER_BUSINESS_ADDRESS"
  val BUSINESS_TYPE = "BUSINESS_TYPE"

}
